services:
    LAG\AdminBundle\Controller\Resource\ResourceController:
        arguments:
            $uriVariablesExtractor: '@lag_admin.request_uri_variables_extractor'
            $contextProvider: '@lag_admin.request.context_provider'
            $dataProvider: '@lag_admin.state.data_provider'
            $dataProcessor: '@lag_admin.state.data_processor'
            $formFactory: '@form.factory'
            $environment: '@twig'
            $responseHandler: '@RedirectionHandler'
        tags: ['controller.service_arguments']

    LAG\AdminBundle\Controller\Resource\ResourceCollectionController:
        arguments:
            $uriVariablesExtractor: '@lag_admin.request_uri_variables_extractor'
            $contextProvider: '@lag_admin.request.context_provider'
            $dataProvider: '@lag_admin.state.data_provider'
            $formFactory: '@form.factory'
            $gridFactory: '@lag_admin.grid.factory'
            $environment: '@twig'
        tags: ['controller.service_arguments']
