services:
    # Resource listeners
    LAG\AdminBundle\EventListener\Resource\ResourceCreateListener:
        arguments:
            $routeNameGenerator: '@lag_admin.routing.route_name_generator'
        tags:
            - { name: kernel.event_listener, event: lag_admin.resource.create, priority: 255 }

    LAG\AdminBundle\EventListener\Resource\ResourceCreatedListener:
        arguments:
            $routeNameGenerator: '@lag_admin.routing.route_name_generator'
        tags:
            - { name: kernel.event_listener, event: lag_admin.resource.created, priority: 255 }

    # Operation listeners
    LAG\AdminBundle\EventListener\Operation\OperationCreateListener:
        tags:
            - { name: kernel.event_listener, event: lag_admin.operation.create, priority: 255 }

    LAG\AdminBundle\EventListener\Property\CreateListener:
        tags:
            - { name: kernel.event_listener, event: lag_admin.property.create, priority: 255 }

    # Security listeners
    LAG\AdminBundle\EventListener\Security\RequestListener:
        arguments:
            $security: '@security.helper'
        tags:
            - { name: kernel.event_listener, event: kernel.controller_arguments, priority: 0 }

    # Data listeners
    LAG\AdminBundle\EventListener\Data\TimestampableListener:
        tags:
            - { name: kernel.event_listener, event: lag_admin.data.process, priority: 255 }
