services:
    lag_admin.resource.dispatcher: '@LAG\AdminBundle\Event\Dispatcher\ResourceEventDispatcher'

    # Resource listeners
    LAG\AdminBundle\EventListener\Resource\ResourceCreateListener:
        arguments:
            $routeNameGenerator: '@lag_admin.routing.route_name_generator'
            $applicationConfiguration: '@lag_admin.application'
        tags:
            - {name: kernel.event_listener, event: lag_admin.resource.create, priority: 255}

    LAG\AdminBundle\EventListener\Resource\ResourceCreatedListener:
        arguments:
            $routeNameGenerator: '@lag_admin.routing.route_name_generator'
        tags:
            - {name: kernel.event_listener, event: lag_admin.resource.created, priority: 255}

    # Operation listeners
    LAG\AdminBundle\EventListener\Operation\DefaultOperationListener:
        tags:
            - {name: kernel.event_listener, event: lag_admin.operation.create, priority: 255}

    LAG\AdminBundle\EventListener\Operation\OperationPathListener:
        tags:
            - {name: kernel.event_listener, event: lag_admin.operation.create, priority: -255}

    # Security listeners
    LAG\AdminBundle\EventListener\Security\OperationPermissionListener:
        arguments:
            $resourceContext: '@lag_admin.resource.context'
            $security: '@security.helper'
        tags:
            - {name: kernel.event_listener, event: kernel.request}

    # Data listeners
    LAG\AdminBundle\EventListener\Data\TimestampableListener:
        tags:
            - {name: kernel.event_listener, event: lag_admin.data.process, priority: 255}

    LAG\AdminBundle\EventListener\Data\SlugListener:
        arguments:
            $generator: '@lag_admin.slug.generator'
            $mapping: '@LAG\AdminBundle\Slug\Mapping\SlugMapping'
        tags:
            - {name: kernel.event_listener, event: lag_admin.data.process, priority: 255}

    # Dispatcher
    LAG\AdminBundle\Event\Dispatcher\ResourceEventDispatcherInterface: '@LAG\AdminBundle\Event\Dispatcher\ResourceEventDispatcher'
    LAG\AdminBundle\Event\Dispatcher\ResourceEventDispatcher:
        arguments:
            $eventDispatcher: '@event_dispatcher'
