services:
    # Resources factories
    lag_admin.resource.factory: '@LAG\AdminBundle\Metadata\Factory\ResourceFactoryInterface'
    LAG\AdminBundle\Metadata\Factory\ResourceFactoryInterface:
        class: LAG\AdminBundle\Metadata\Factory\ResourceFactory
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $operationFactory: '@lag_admin.operation.factory'

    LAG\AdminBundle\Metadata\Factory\ResourceFactoryValidationDecorator:
        decorates: 'lag_admin.resource.factory'
        decoration_priority: 0
        arguments:
            $validator: '@validator'
            $decorated: '@.inner'

    LAG\AdminBundle\Metadata\Factory\ResourceFactoryCacheDecorator:
        decorates: 'lag_admin.resource.factory'
        decoration_priority: -10
        arguments:
            $decorated: '@.inner'

    # Operations factories
    lag_admin.operation.factory: '@LAG\AdminBundle\Metadata\Factory\OperationFactoryInterface'
    LAG\AdminBundle\Metadata\Factory\OperationFactoryInterface:
        class: LAG\AdminBundle\Metadata\Factory\OperationFactory
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $propertyFactory: '@lag_admin.property.factory'
            $filterFactory: '@lag_admin.filter.factory'

    # Properties factories
    lag_admin.property.factory: '@LAG\AdminBundle\Metadata\Factory\PropertyFactoryInterface'
    LAG\AdminBundle\Metadata\Factory\PropertyFactoryInterface:
        class: LAG\AdminBundle\Metadata\Factory\PropertyFactory
        arguments:
            $validator: '@validator'
