services:
    lag_admin.filter.factory: '@LAG\AdminBundle\Filter\Factory\FilterFactoryInterface'
    LAG\AdminBundle\Filter\Factory\FilterFactoryInterface:
        class: LAG\AdminBundle\Filter\Factory\FilterFactory
        arguments:
            $validator: '@validator'

    LAG\AdminBundle\Filter\Factory\EventFilterFactory:
        decorates: 'lag_admin.filter.factory'
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $decorated: '@.inner'
