services:
    lag_admin.grid.factory: '@LAG\AdminBundle\Grid\Factory\GridFactory'
    LAG\AdminBundle\Grid\Factory\GridFactoryInterface: '@LAG\AdminBundle\Grid\Factory\GridFactory'
    LAG\AdminBundle\Grid\Factory\GridFactory:
        arguments:
            $cellFactory: '@lag_admin.grid.cell_factory'
            $eventDispatcher: '@event_dispatcher'

    lag_admin.grid.cell_factory: '@LAG\AdminBundle\Grid\Factory\CellFactory'
    LAG\AdminBundle\Grid\Factory\CellFactoryInterface: '@LAG\AdminBundle\Grid\Factory\CellFactory'
    LAG\AdminBundle\Grid\Factory\CellFactory:
        arguments:
            $dataTransformer: '@lag_admin.grid.data_transformer'

    lag_admin.grid.data_transformer: '@LAG\AdminBundle\Grid\DataTransformer\DataTransformer'
    LAG\AdminBundle\Grid\DataTransformer\DataTransformerInterface: '@LAG\AdminBundle\Grid\DataTransformer\DataTransformer'
    LAG\AdminBundle\Grid\DataTransformer\DataTransformer:
        arguments:
            $transformers: !tagged_iterator lag_admin.grid.data_transformer

    LAG\AdminBundle\Grid\DataTransformer\CountDataTransformer:
        tags:
            - { name: 'lag_admin.grid.data_transformer', priority: -255 }

    lag_admin.grid.renderer: '@LAG\AdminBundle\Grid\View\GridRenderer'
    LAG\AdminBundle\Grid\View\GridRendererInterface: '@LAG\AdminBundle\Grid\View\GridRenderer'
    LAG\AdminBundle\Grid\View\GridRenderer:
        arguments:
            $environment: '@twig'


    lag_admin.grid.cell_renderer: '@LAG\AdminBundle\Grid\View\CellRenderer'
    LAG\AdminBundle\Grid\View\CellRendererInterface: '@LAG\AdminBundle\Grid\View\CellRenderer'
    LAG\AdminBundle\Grid\View\CellRenderer:
        arguments:
            $environment: '@twig'














    # TODO remove
    lag_admin.grid.field_renderer: '@LAG\AdminBundle\Field\Render\FieldRenderer'
    LAG\AdminBundle\Field\Render\FieldRendererInterface: '@LAG\AdminBundle\Field\Render\FieldRenderer'
    LAG\AdminBundle\Field\Render\FieldRenderer:
        autowire: true
