services:
    # Factories
    lag_admin.grid.factory: '@LAG\AdminBundle\Grid\Factory\GridFactory'
    LAG\AdminBundle\Grid\Factory\GridFactoryInterface: '@LAG\AdminBundle\Grid\Factory\GridFactory'
    LAG\AdminBundle\Grid\Factory\GridFactory:
        arguments:
            $registry: '@lag_admin.grid.registry'
            $cellFactory: '@lag_admin.grid.cell_factory'
            $eventDispatcher: '@event_dispatcher'

    lag_admin.grid.cell_factory: '@LAG\AdminBundle\Grid\Factory\CellFactory'
    LAG\AdminBundle\Grid\Factory\CellFactoryInterface: '@LAG\AdminBundle\Grid\Factory\CellFactory'
    LAG\AdminBundle\Grid\Factory\CellFactory: ~

    lag_admin.grid.renderer: '@LAG\AdminBundle\Grid\View\GridRenderer'
    LAG\AdminBundle\Grid\View\GridRendererInterface: '@LAG\AdminBundle\Grid\View\GridRenderer'
    LAG\AdminBundle\Grid\View\GridRenderer:
        arguments:
            $environment: '@twig'


    lag_admin.grid.cell_renderer: '@LAG\AdminBundle\Grid\View\CellRenderer'
    LAG\AdminBundle\Grid\View\CellRendererInterface: '@LAG\AdminBundle\Grid\View\CellRenderer'
    LAG\AdminBundle\Grid\View\CellRenderer:
        arguments:
            $environment: '@twig'


    lag_admin.grid.registry: '@LAG\AdminBundle\Grid\Registry\GridRegistryInterface'
    LAG\AdminBundle\Grid\Registry\GridRegistryInterface:
        class: LAG\AdminBundle\Grid\Registry\GridRegistry
        arguments:
            $validator: '@validator'
            $gridsConfiguration: '%lag_admin.grids%'


    # Validation
    LAG\AdminBundle\Validation\Validator\GridExistValidator:
        arguments:
            $registry: '@lag_admin.grid.registry'
        tags: ['validator.constraint_validator']








    # TODO remove
    lag_admin.grid.field_renderer: '@LAG\AdminBundle\Field\Render\FieldRenderer'
    LAG\AdminBundle\Field\Render\FieldRendererInterface: '@LAG\AdminBundle\Field\Render\FieldRenderer'
    LAG\AdminBundle\Field\Render\FieldRenderer:
        autowire: true
