services:
    # Controller parameter resolvers
    LAG\AdminBundle\Request\Resolver\ResourceValueResolver:
        arguments:
            $resourceContext: '@lag_admin.resource.context'
        tags:
            - {name: controller.argument_value_resolver, priority: 255}

    lag_admin.request.parameters_extractor: '@LAG\AdminBundle\Request\Extractor\ParametersExtractorInterface'
    LAG\AdminBundle\Request\Extractor\ParametersExtractorInterface:
        class: LAG\AdminBundle\Request\Extractor\ParametersExtractor

    lag_admin.request_uri_variables_extractor: '@LAG\AdminBundle\Request\Uri\UriVariablesExtractorInterface'
    LAG\AdminBundle\Request\Uri\UriVariablesExtractorInterface:
        class: LAG\AdminBundle\Request\Uri\UriVariablesExtractor

    # Request context resolvers
    lag_admin.request.context_provider: '@LAG\AdminBundle\Request\Context\ContextProviderInterface'
    LAG\AdminBundle\Request\Context\ContextProviderInterface:
        class: LAG\AdminBundle\Request\Context\CompositeContextProvider
        arguments:
            $contextProviders: !tagged_iterator lag_admin.request_context_provider

    LAG\AdminBundle\Request\Context\SortingContextProvider:
        tags:
            - {name: lag_admin.request_context_provider, priority: 255}

    LAG\AdminBundle\Request\Context\AjaxContextProvider:
        tags:
            - {name: lag_admin.request_context_provider, priority: 255}

    LAG\AdminBundle\Request\Context\FilterContextProvider:
        arguments:
            $formFactory: '@form.factory'
        tags:
            - {name: lag_admin.request_context_provider, priority: 255}

    # Redirection handler
    LAG\AdminBundle\Response\Handler\ResponseHandlerInterface:
        class: LAG\AdminBundle\Response\Handler\ResponseHandler
        arguments:
            $urlGenerator: '@LAG\AdminBundle\Routing\UrlGenerator\UrlGenerator'
