services:
    lag_admin.resource.registry: '@LAG\AdminBundle\Resource\Registry\ResourceRegistry'
    LAG\AdminBundle\Resource\Registry\ResourceRegistryInterface: '@LAG\AdminBundle\Resource\Registry\ResourceRegistry'
    LAG\AdminBundle\Resource\Registry\ResourceRegistry:
        arguments:
            $resourcesPath: '%lag_admin.resources.paths%'
            $locator: '@lag_admin.resource.locator'

    lag_admin.resource.locator: '@LAG\AdminBundle\Resource\Locator\CompositeLocator'
    LAG\AdminBundle\Resource\Locator\ResourceLocatorInterface: '@LAG\AdminBundle\Resource\Locator\CompositeLocator'
    LAG\AdminBundle\Resource\Locator\CompositeLocator:
        arguments:
            $locators: !tagged_iterator lag_admin.resource.locator

    LAG\AdminBundle\Resource\Locator\AttributeLocator:
        tags: ['lag_admin.resource.locator']

    LAG\AdminBundle\Resource\Locator\YamlLocator:
        tags: ['lag_admin.resource.locator']

