services:
    _defaults:
        autowire: true
        autoconfigure: true

    LAG\AdminBundle\Routing\Loader\RoutingLoader:
        tags:
            - { name: routing.loader }

    LAG\AdminBundle\Routing\Loader\ResourceLoaderInterface: '@LAG\AdminBundle\Routing\Loader\ResourceLoader'
    LAG\AdminBundle\Routing\Loader\ResourceLoader: ~

    LAG\AdminBundle\Routing\Redirection\RedirectionUtils: ~

    LAG\AdminBundle\Routing\Route\RouteNameGeneratorInterface: '@LAG\AdminBundle\Routing\Route\RouteNameGenerator'
    LAG\AdminBundle\Routing\Route\RouteNameGenerator: ~

    LAG\AdminBundle\Routing\UrlGenerator\UrlGeneratorInterface: '@LAG\AdminBundle\Routing\UrlGenerator\UrlGenerator'
    LAG\AdminBundle\Routing\UrlGenerator\UrlGenerator: ~

    lag_admin.routing.url_resolver: '@LAG\AdminBundle\Routing\Resolver\RoutingUrlResolver'
    LAG\AdminBundle\Routing\Resolver\RoutingUrlResolverInterface: '@LAG\AdminBundle\Routing\Resolver\RoutingUrlResolver'
    LAG\AdminBundle\Routing\Resolver\RoutingUrlResolver:
        arguments:
            $router: '@router'
            $urlGenerator: '@LAG\AdminBundle\Routing\UrlGenerator\UrlGeneratorInterface'
            $routeNameGenerator: '@LAG\AdminBundle\Routing\Route\RouteNameGeneratorInterface'
