services:
    LAG\AdminBundle\Routing\Loader\ResourceRoutingLoader:
        arguments:
            $pathGenerator: '@lag_admin.routing.path_generator'
            $resourceRegistry: '@lag_admin.resource.registry'
        tags: ['routing.loader']

    lag_admin.routing.route_name_generator: '@LAG\AdminBundle\Routing\Route\RouteNameGenerator'
    LAG\AdminBundle\Routing\Route\RouteNameGeneratorInterface: '@LAG\AdminBundle\Routing\Route\RouteNameGenerator'
    LAG\AdminBundle\Routing\Route\RouteNameGenerator:

    lag_admin.routing.url_generator: '@LAG\AdminBundle\Routing\UrlGenerator\UrlGenerator'
    LAG\AdminBundle\Routing\UrlGenerator\UrlGeneratorInterface: '@LAG\AdminBundle\Routing\UrlGenerator\UrlGenerator'
    LAG\AdminBundle\Routing\UrlGenerator\UrlGenerator:
        arguments:
            $router: '@router'
            $resourceRegistry: '@lag_admin.resource.registry'

    lag_admin.routing.path_generator: '@LAG\AdminBundle\Routing\UrlGenerator\PathGeneratorInterface'
    LAG\AdminBundle\Routing\UrlGenerator\PathGeneratorInterface: '@LAG\AdminBundle\Routing\UrlGenerator\PathGenerator'
    LAG\AdminBundle\Routing\UrlGenerator\PathGenerator: ~
