services:
    lag_admin.security.helper: '@LAG\AdminBundle\Security\Helper\SecurityHelper'
    LAG\AdminBundle\Security\Helper\SecurityHelper:
        arguments:
            $security: '@security.helper'
            $registry: '@lag_admin.resource.registry'
