services:
    # Generators
    lag_admin.slug.generator: '@LAG\AdminBundle\Slug\Generator\CompositeSlugGenerator'
    LAG\AdminBundle\Slug\Generator\SlugGeneratorInterface: '@LAG\AdminBundle\Slug\Generator\CompositeSlugGenerator'
    LAG\AdminBundle\Slug\Generator\CompositeSlugGenerator: ~

    LAG\AdminBundle\Slug\Generator\SimpleSlugGenerator:
        tags:
            - {name: lag_admin.slug_generator, generator: default}

    # Mapping
    LAG\AdminBundle\Slug\Mapping\SlugMappingInterface: '@LAG\AdminBundle\Slug\Mapping\SlugMapping'
    LAG\AdminBundle\Slug\Mapping\SlugMapping:
        arguments:
            $registry: '@lag_admin.resource.registry'
