services:
    lag_admin.state.data_provider: '@LAG\AdminBundle\State\DataProviderInterface'
    LAG\AdminBundle\State\DataProviderInterface:
        class: LAG\AdminBundle\State\CompositeDataProvider
        arguments:
            $providers: !tagged_iterator lag_admin.data_provider

    lag_admin.state.data_processor: '@LAG\AdminBundle\State\DataProcessorInterface'
    LAG\AdminBundle\State\DataProcessorInterface:
        class: LAG\AdminBundle\State\CompositeDataProcessor
        arguments:
            $processors: !tagged_iterator lag_admin.data_processor

    LAG\AdminBundle\State\EventDataProcessor:
        decorates: 'lag_admin.state.data_processor'
        arguments:
            $decorated: '@.inner'
            $eventDispatcher: '@event_dispatcher'
