services:
    lag_admin.state.data_provider: '@LAG\AdminBundle\State\Provider\DataProviderInterface'
    lag_admin.state.data_processor: '@LAG\AdminBundle\State\Processor\DataProcessorInterface'

    # Data providers
    LAG\AdminBundle\State\Provider\DataProviderInterface:
        class: LAG\AdminBundle\State\Provider\CompositeDataProvider
        arguments:
            $providers: !tagged_iterator lag_admin.data_provider

    LAG\AdminBundle\State\Provider\JsonDataProviderDecorator:
        decorates: lag_admin.state.data_provider
        arguments:
            $decorated: '@.inner'
            $serializer: '@serializer'

    # Data processors
    LAG\AdminBundle\State\Processor\DataProcessorInterface:
        class: LAG\AdminBundle\State\Processor\CompositeDataProcessor
        arguments:
            $processors: !tagged_iterator lag_admin.data_processor
            $eventDispatcher: '@lag_admin.resource.dispatcher'
