services:
    LAG\AdminBundle\Twig\Extension\AdminExtension:
        arguments:
            $applicationConfiguration: '@lag_admin.application'
            $security: '@lag_admin.security.helper'
            $actionRenderer: '@lag_admin.action.renderer'
            $urlGenerator: '@lag_admin.routing.url_generator'
        tags: ['twig.extension']

    LAG\AdminBundle\Twig\Extension\GridExtension:
        arguments:
            $gridRenderer: '@lag_admin.grid.renderer'
            $cellRenderer: '@lag_admin.grid.cell_renderer'
        tags: ['twig.extension']

    LAG\AdminBundle\Twig\Extension\MessageExtension:
        arguments:
            $registry: '@LAG\AdminBundle\Message\Registry\NotificationRegistryInterface'
        tags: ['twig.extension']

    LAG\AdminBundle\Twig\Extension\TranslationExtension:
        arguments:
            $translator: '@translator'
            $configuration: '@lag_admin.application'
        tags: ['twig.extension']

    LAG\AdminBundle\Twig\Extension\StringExtension:
        tags: ['twig.extension']
