services:
    LAG\AdminBundle\Twig\Extension\AdminExtension:
        arguments:
            $mediaBundleEnabled: '%lag_admin.media_bundle_enabled%'
            $applicationConfiguration: '@lag_admin.application'
            $security: '@lag_admin.security.helper'
            $actionRenderer: '@lag_admin.action.renderer'
            $urlGenerator: '@lag_admin.routing.url_generator'
        tags: ['twig.extension']

    LAG\AdminBundle\Twig\Extension\GridExtension:
        arguments:
            $gridRenderer: '@lag_admin.grid.renderer'
            $cellRenderer: '@lag_admin.grid.cell_renderer'
        tags: ['twig.extension']

    LAG\AdminBundle\Twig\Extension\StringExtension:
        arguments:
            $configuration: '@lag_admin.application'
            $translator: '@translator'
        tags: ['twig.extension']
