services:
    lag_admin.action.renderer: '@LAG\AdminBundle\Twig\Render\ActionRendererInterface'
    LAG\AdminBundle\Twig\Render\ActionRendererInterface:
        class: LAG\AdminBundle\Twig\Render\ActionRenderer
        arguments:
            $urlGenerator: '@lag_admin.routing.url_generator'
            $validator: '@validator'
            $environment: '@twig'
