services:
    lag_admin.action.renderer: '@LAG\AdminBundle\Action\Render\ActionRendererInterface'
    LAG\AdminBundle\Action\Render\ActionRendererInterface:
        class: LAG\AdminBundle\Action\Render\ActionRenderer
        arguments:
            $urlGenerator: '@lag_admin.routing.url_generator'
            $validator: '@validator'
            $environment: '@twig'






































    # Factories
    LAG\AdminBundle\View\Factory\ViewFactoryInterface: '@LAG\AdminBundle\View\Factory\ViewFactory'
    LAG\AdminBundle\View\Factory\ViewFactory: ~

    # Handlers
    LAG\AdminBundle\View\Handler\ViewHandlerInterface: '@LAG\AdminBundle\View\Handler\ViewHandler'
    LAG\AdminBundle\View\Handler\ViewHandler: ~
