services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Admin objects factories
    LAG\AdminBundle\Factory\ActionFactoryInterface: '@LAG\AdminBundle\Action\Factory\ActionFactory'
    LAG\AdminBundle\Factory\ActionFactory: ~
    
    LAG\AdminBundle\Factory\AdminFactoryInterface: '@LAG\AdminBundle\Admin\Factory\AdminFactory'
    LAG\AdminBundle\Factory\AdminFactory: ~

    LAG\AdminBundle\Factory\FieldFactoryInterface: '@LAG\AdminBundle\Factory\FieldFactory'
    LAG\AdminBundle\Factory\FieldFactory:
        arguments:
            $fieldsMapping: '%lag_admin.fields.mapping%'

    LAG\AdminBundle\Form\Factory\FormFactoryInterface: '@LAG\AdminBundle\Form\Factory\FormFactory'
    LAG\AdminBundle\Form\Factory\FormFactory: ~
    
    LAG\AdminBundle\Factory\Form\FilterFormFactoryInterface: '@LAG\AdminBundle\Factory\Form\FilterFormFactory'
    LAG\AdminBundle\Factory\Form\FilterFormFactory: ~

    # Configuration factories
    LAG\AdminBundle\Factory\Configuration\AdminConfigurationFactoryInterface: '@LAG\AdminBundle\Admin\Factory\AdminConfigurationFactory'
    LAG\AdminBundle\Factory\Configuration\AdminConfigurationFactory: ~

    LAG\AdminBundle\Factory\Configuration\ActionConfigurationFactoryInterface: '@LAG\AdminBundle\Action\Factory\ActionConfigurationFactory'
    LAG\AdminBundle\Factory\Configuration\ActionConfigurationFactory: ~
