services:
    LAG\AdminBundle\Resource\Registry\ResourceRegistryInterface: '@LAG\AdminBundle\Resource\Registry\ResourceRegistry'
    LAG\AdminBundle\Resource\Registry\ResourceRegistry:
        arguments:
            $resourcesPath: '%lag_admin.resources.paths%'
