services:
    _defaults:
        autowire: true
        autoconfigure: true

    lag_admin.security.helper: '@LAG\AdminBundle\Security\Helper\SecurityHelper'

    LAG\AdminBundle\Security\Helper\SecurityHelper:
