services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Data handlers
    LAG\AdminBundle\Bridge\Doctrine\DataHandler\ResultsHandler:
        tags:
            - {name: lag.admin.data_handler, priority: -255}

    # Data provider
    LAG\AdminBundle\Bridge\Doctrine\ORMDataProvider:
        tags:
            - { name: lag.admin.data_provider, identifier: doctrine }

    LAG\AdminBundle\Bridge\Doctrine\ORMDataPersister:
        tags:
            - {name: lag.admin.data_persister, identifier: doctrine}

    LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelperInterface: '@LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelper'
    LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelper:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # Event listeners
    LAG\AdminBundle\Bridge\Doctrine\Event\Listener\CreateFieldDefinitionListener:
        tags:
            - {name: kernel.event_listener, event: lag.admin.field_definition_create, priority: 0}

    LAG\AdminBundle\Bridge\Doctrine\Event\Listener\FilterListener:
        tags:
            - {name: kernel.event_listener, event: lag.admin.data_filter, priority: 255}

    LAG\AdminBundle\Bridge\Doctrine\Event\Listener\OrderListener:
        tags:
            - {name: kernel.event_listener, event: lag.admin.data_order, priority: 254}
