services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    LAG\AdminBundle\DataProvider\Registry\DataProviderRegistryInterface: '@LAG\AdminBundle\DataProvider\Registry\DataProviderRegistry'
    LAG\AdminBundle\DataProvider\Registry\DataProviderRegistry:
        arguments:
            - !tagged_iterator {tag: lag.admin.data_provider, index_by: identifier}

    LAG\AdminBundle\DataPersister\Registry\DataPersisterRegistryInterface: '@LAG\AdminBundle\DataPersister\Registry\DataPersisterRegistry'
    LAG\AdminBundle\DataPersister\Registry\DataPersisterRegistry:
        arguments:
            - !tagged_iterator {tag: lag.admin.data_persister, index_by: identifier}
