services:
    LAG\AdminBundle\Bridge\KnpMenu\Provider\MenuProvider:
        arguments:
            $menuConfigurations: '%lag.menus%'
            $factory: '@knp_menu.factory'
            $configurationFactory: '@LAG\AdminBundle\Factory\ConfigurationFactory'
            $resolver: '@LAG\AdminBundle\Routing\Resolver\RoutingResolverInterface'
            $adminHelper: '@LAG\AdminBundle\Admin\Helper\AdminHelperInterface'
            $requestStack: '@request_stack'
        tags:
            - {name: knp_menu.provider}

    LAG\AdminBundle\Event\Subscriber\MenuSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\MenuSubscriber
        arguments:
            $menuEnabled: '%lag.enable_menus%'
            $registry: '@LAG\AdminBundle\Resource\Registry\ResourceRegistryInterface'
            $adminHelper: '@LAG\AdminBundle\Admin\Helper\AdminHelperInterface'
            $menuConfigurations: '%lag.menus%'
        tags:
            - {name: kernel.event_subscriber}
