services:
    _defaults:
        autoconfigure: true
        autowire: true
    
    LAG\AdminBundle\Menu\Provider\MenuProvider:
        arguments:
            $menuConfigurations: '%lag_admin.menu.menus%'
        tags:
            - {name: knp_menu.provider}

    LAG\AdminBundle\Event\Listener\Menu\DefaultMenuListener:
        arguments:
            $menuEnabled: '%lag_admin.menu.enable%'
            $menuConfigurations: '%lag_admin.menu.menus%'
        tags:
            - {name: kernel.event_listener, event: lag.admin.menu_configuration, priority: 255}
    
    LAG\AdminBundle\Event\Listener\Menu\MenuConfigurationListener:
        tags:
            - {name: kernel.event_listener, event: lag.admin.menu_configuration, priority: 0}
