services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    LAG\AdminBundle\Utils\RedirectionUtils: ~
    
    LAG\AdminBundle\Routing\UrlGenerator\UrlGeneratorInterface: '@LAG\AdminBundle\Routing\UrlGenerator\UrlGenerator'
    LAG\AdminBundle\Routing\UrlGenerator\UrlGenerator: ~
