services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LAG\AdminBundle\Event\Subscriber\SecuritySubscriber:
        class: LAG\AdminBundle\Event\Subscriber\SecuritySubscriber

    LAG\AdminBundle\Event\Subscriber\AdminSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\AdminSubscriber

    LAG\AdminBundle\Event\Subscriber\FormSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\FormSubscriber

    LAG\AdminBundle\Event\Subscriber\ExtraConfigurationSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\ExtraConfigurationSubscriber

    LAG\AdminBundle\Event\Subscriber\MenuSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\MenuSubscriber

    LAG\AdminBundle\Bridge\Doctrine\ORM\Event\Subscriber\ORMSubscriber:
        class: LAG\AdminBundle\Bridge\Doctrine\ORM\Event\Subscriber\ORMSubscriber

    LAG\AdminBundle\Event\Subscriber\FilterSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\FilterSubscriber
