services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LAG\AdminBundle\Twig\Extension\AdminExtension:
        arguments:
            $mediaEnabled: '%lag_admin.media_bundle_enabled%'
        tags:
            - {name: twig.extension}

    LAG\AdminBundle\Twig\Extension\FieldExtension:
        tags:
            - {name: twig.extension}

    LAG\AdminBundle\Twig\Extension\MessageExtension:
        tags:
            - {name: twig.extension}

    LAG\AdminBundle\Twig\Extension\MenuExtension:
        tags:
            - {name: twig.extension}

    LAG\AdminBundle\Twig\Extension\RoutingExtension:
        tags:
            - {name: twig.extension}

    LAG\AdminBundle\Twig\Extension\TranslationExtension:
        tags:
            - {name: twig.extension}
