services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    LAG\AdminBundle\Bridge\Twig\Extension\AdminExtension:
        tags:
            - {name: twig.extension}

    LAG\AdminBundle\Bridge\Twig\Extension\FieldExtension:
        tags:
            - {name: twig.extension}

    LAG\AdminBundle\Bridge\Twig\Extension\MenuExtension:
        tags:
            - {name: twig.extension}
