parameters:
    # admin factories
    lag.admin.factory: LAG\AdminBundle\Admin\Factory\AdminFactory
    lag.admin.action_factory: LAG\AdminBundle\Action\Factory\ActionFactory
    lag.admin.field_factory: LAG\AdminBundle\Field\Factory\FieldFactory
    lag.admin.filter_factory: LAG\AdminBundle\Admin\Factory\FilterFactory
    lag.admin.configuration_factory: LAG\AdminBundle\Configuration\Factory\ConfigurationFactory

services:
    # factories
    lag.admin.configuration_factory:
        class: '%lag.admin.configuration_factory%'
        arguments:
            - '@kernel'
        calls:
            - ['createApplicationConfiguration', ['%lag.admin.application_configuration%']]

    lag.admin.factory:
        class: '%lag.admin.factory%'
        arguments:
            - '%lag.admins%'
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'
            - '@lag.admin.configuration_factory'
            - '@lag.admin.action_factory'
            - '@lag.admin.message_handler'

    lag.admin.action_factory:
        class: '%lag.admin.action_factory%'
        arguments:
            - '@lag.admin.field_factory'
            - '@lag.admin.filter_factory'
            - '@lag.admin.configuration_factory'

    lag.admin.field_factory:
        class: '%lag.admin.field_factory%'
        arguments:
            - '@lag.admin.configuration_factory'
            - '@translator'
            - '@twig'

    lag.admin.filter_factory:
        class: '%lag.admin.filter_factory%'
        arguments: []
