parameters:
    # admin factories
    bluebear.admin.factory: BlueBear\AdminBundle\Admin\Factory\AdminFactory
    bluebear.admin.action_factory: BlueBear\AdminBundle\Admin\Factory\ActionFactory
    bluebear.admin.field_factory: BlueBear\AdminBundle\Admin\Factory\FieldFactory
    bluebear.admin.field_renderer_factory: BlueBear\AdminBundle\Admin\Factory\FieldRendererFactory
    bluebear.admin.filter_factory: BlueBear\AdminBundle\Admin\Factory\FilterFactory

services:
    # factories
    bluebear.admin.factory:
        class: %bluebear.admin.factory%
        arguments: [@service_container, @bluebear.admin.routing]

    bluebear.admin.action_factory:
        class: %bluebear.admin.action_factory%
        arguments: [@bluebear.admin.routing, @bluebear.admin.field_factory, @bluebear.admin.filter_factory, @bluebear.admin.application]

    bluebear.admin.field_factory:
        class: %bluebear.admin.field_factory%
        arguments: [@bluebear.admin.application]
        calls:
            - [setContainer, [@service_container]]

    bluebear.admin.filter_factory:
        class: %bluebear.admin.filter_factory%
        arguments: []
