parameters:
    # admin factories
    lag.admin.factory: LAG\AdminBundle\Admin\Factory\AdminFactory
    lag.admin.action_factory: LAG\AdminBundle\Admin\Factory\ActionFactory
    lag.admin.field_factory: LAG\AdminBundle\Admin\Factory\FieldFactory
    lag.admin.field_renderer_factory: LAG\AdminBundle\Admin\Factory\FieldRendererFactory
    lag.admin.filter_factory: LAG\AdminBundle\Admin\Factory\FilterFactory

services:
    # factories
    lag.admin.factory:
        class: %lag.admin.factory%
        arguments: [@service_container, @lag.admin.routing]

    lag.admin.action_factory:
        class: %lag.admin.action_factory%
        arguments: [@lag.admin.routing, @lag.admin.field_factory, @lag.admin.filter_factory, @lag.admin.application]

    lag.admin.field_factory:
        class: %lag.admin.field_factory%
        arguments: [@lag.admin.application]
        calls:
            - [setContainer, [@service_container]]

    lag.admin.filter_factory:
        class: %lag.admin.filter_factory%
        arguments: []
