services:
    lag.admin.configuration_factory:
        class: LAG\AdminBundle\Configuration\Factory\ConfigurationFactory
        calls:
            - ['createApplicationConfiguration', ['%lag.admin.application_configuration%']]

    lag.admin.factory:
        class: LAG\AdminBundle\Admin\Factory\AdminFactory
        arguments:
            - '%lag.admins%'
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'
            - '@lag.admin.configuration_factory'
            - '@lag.admin.action_factory'
            - '@lag.admin.message_handler'

    lag.admin.action_factory:
        class: LAG\AdminBundle\Action\Factory\ActionFactory
        arguments:
            - '@lag.admin.field_factory'
            - '@lag.admin.filter_factory'
            - '@lag.admin.configuration_factory'

    lag.admin.field_factory:
        class: LAG\AdminBundle\Field\Factory\FieldFactory
        arguments:
            - '@lag.admin.configuration_factory'
            - '@translator'
            - '@twig'

    lag.admin.filter_factory:
        class: LAG\AdminBundle\Admin\Factory\FilterFactory
        arguments: []

    lag.admin.menu_factory:
        class: LAG\AdminBundle\Menu\Factory\MenuFactory
        arguments:
            - '@knp_menu.factory'
            - '@lag.admin.factory'
            - '@lag.admin.configuration_factory'
            - '@translator'
