parameters:
    lag.admin.field.string.class: LAG\AdminBundle\Admin\Field\StringField
    lag.admin.field.date.class: LAG\AdminBundle\Admin\Field\Date
    lag.admin.field.count.class: LAG\AdminBundle\Admin\Field\Count
    lag.admin.field.link.class: LAG\AdminBundle\Admin\Field\Link
    lag.admin.field.action.class: LAG\AdminBundle\Admin\Field\Action
    lag.admin.field.collection.class: LAG\AdminBundle\Admin\Field\Collection
    lag.admin.field.array.class: LAG\AdminBundle\Admin\Field\ArrayField
    lag.admin.field.boolean.class: LAG\AdminBundle\Admin\Field\Boolean

services:
    # String field
    lag.admin.field.string:
        class: %lag.admin.field.string.class%
        scope: prototype
        tags:
            -  { name: lag.field, type: string }
        calls:
            - [setTranslator, [@translator]]

    # Date field
    lag.admin.field.date:
        class: %lag.admin.field.date.class%
        scope: prototype
        tags:
            -  { name: lag.field, type: date }

    # Count field
    lag.admin.field.count:
        class: %lag.admin.field.count.class%
        scope: prototype
        tags:
            -  { name: lag.field, type: count }

    # Link field
    lag.admin.field.link:
        class: %lag.admin.field.link.class%
        scope: prototype
        tags:
            -  { name: lag.field, type: link }
        calls:
            - [setTwig, [@twig]]

    # Action field
    lag.admin.field.action:
        class: %lag.admin.field.action.class%
        scope: prototype
        tags:
            -  { name: lag.field, type: action }
        calls:
            - [setTwig, [@twig]]

    # Collections of fields
    lag.admin.field.collection:
        class: %lag.admin.field.collection.class%
        scope: prototype
        tags:
            -  { name: lag.field, type: collection }
        calls:
            - [setTwig, [@twig]]

    # Array field
    lag.admin.field.array:
        class: %lag.admin.field.array.class%
        scope: prototype
        tags:
            -  { name: lag.field, type: array }

    # Boolean field
    lag.admin.field.boolean:
        class: %lag.admin.field.boolean.class%
        scope: prototype
        tags:
            -  { name: lag.field, type: boolean }
        calls:
            - [setTranslator, [@translator]]
