parameters:
    # form
    bluebear.admin.form.delete.class: BlueBear\AdminBundle\Form\Type\DeleteType
    bluebear.admin.form.datetime_picker.class: BlueBear\AdminBundle\Form\Type\DateTimePickerType

services:
    # form
    bluebear.admin.form.delete:
        class: %bluebear.admin.form.delete.class%
        tags:
            - {name: form.type, alias: delete}

    bluebear.admin.form.datetime_picker:
        class: %bluebear.admin.form.datetime_picker.class%
        tags:
            - {name: form.type, alias: datetime_picker}
        calls:
            - [setConfiguration, [@bluebear.admin.application]]
