services:
    lag.admin.menu_builder:
        class: LAG\AdminBundle\Menu\MenuBuilder
        arguments:
            - '%lag.menus%'
            - '@lag.admin.menu_factory'
            - '@lag.admin.factory'
            - '@request_stack'
        tags:
            - {name: knp_menu.menu_builder, method: mainMenu, alias: main}
            - {name: knp_menu.menu_builder, method: topMenu, alias: top}
