imports:
    - { resource: factories.yml }
    - { resource: forms.yml }
    - { resource: fields.yml }

parameters:
    # application
    lag.admin.application_class: LAG\AdminBundle\Admin\Configuration\ApplicationConfiguration
    # template listener
    lag.admin.template_listener: LAG\AdminBundle\Event\Subscriber\TemplateListener
    # routing
    lag.admin.routing: LAG\AdminBundle\Routing\RoutingLoader
    # twig
    lag.admin.twig: LAG\AdminBundle\Twig\AdminExtension

services:
    # application
    lag.admin.application:
        class: %lag.admin.application_class%
        arguments: [%lag.admin.application_configuration%, %locale%]

    # template listener
    lag.admin.template_listener:
        class: %lag.admin.template_listener%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, [@service_container]]
            - [setAdminFactory, [@lag.admin.factory]]
            - [setTwig, [@twig]]

    # routing
    lag.admin.routing:
        class: %lag.admin.routing%
        tags:
            - { name: routing.loader }
        calls:
            - [setContainer, [@service_container]]

    # twig
    lag.admin.twig:
        class: %lag.admin.twig%
        tags:
            - {name: twig.extension}
        arguments: [@router, @translator, @lag.admin.application]
