imports:
    - { resource: factories.yml }

parameters:
    # application
    bluebear.admin.application_class: BlueBear\AdminBundle\Admin\Configuration\ApplicationConfiguration
    # template listener
    bluebear.admin.template_listener: BlueBear\AdminBundle\Event\Subscriber\TemplateListener
    # form
    bluebear.admin.form.delete: BlueBear\AdminBundle\Form\Type\DeleteType
    # routing
    bluebear.admin.routing: BlueBear\AdminBundle\Routing\RoutingLoader
    # twig
    bluebear.admin.twig: BlueBear\AdminBundle\Twig\AdminExtension

services:
    # application
    bluebear.admin.application:
        class: %bluebear.admin.application_class%
        arguments: [%bluebear.admin.application_configuration%, %locale%]

    # template listener
    bluebear.admin.template_listener:
        class: %bluebear.admin.template_listener%
        tags:
            - {name: kernel.event_subscriber}
        calls:
            - [setContainer, [@service_container]]
            - [setAdminFactory, [@bluebear.admin.factory]]
            - [setTwig, [@twig]]

    # form
    bluebear.admin.form.delete:
        class: %bluebear.admin.form.delete%
        tags:
            - {name: form.type, alias: delete}

    # routing
    bluebear.admin.routing:
        class: %bluebear.admin.routing%
        tags:
            - { name: routing.loader }
        calls:
            - [setContainer, [@service_container]]

    # twig
    bluebear.admin.twig:
        class: %bluebear.admin.twig%
        tags:
            - {name: twig.extension}
        calls:
            - [setRouter, [@router]]
