imports:
    - { resource: factories.yml }
    - { resource: forms.yml }

parameters:
    # application
    lag.admin.application.class: LAG\AdminBundle\Application\Configuration\ApplicationConfiguration
    # events subscribers
    lag.admin.template_subscriber.class: LAG\AdminBundle\Event\Subscriber\TemplateSubscriber
    lag.admin.extra_configuration_subscriber.class: LAG\AdminBundle\Event\Subscriber\ExtraConfigurationSubscriber
    lag.admin.admin_subscriber.class: LAG\AdminBundle\Event\Subscriber\AdminSubscriber
    # routing
    lag.admin.routing.class: LAG\AdminBundle\Routing\RoutingLoader
    # twig
    lag.admin.twig.class: LAG\AdminBundle\Twig\AdminExtension
    # handler
    lag.admin.message_handler.class: LAG\AdminBundle\Message\MessageHandler

services:
    # events subscribers
    lag.admin.template_subscriber:
        class: '%lag.admin.template_subscriber.class%'
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - '@twig'
            - '@lag.admin.application'

    lag.admin.extra_configuration_subscriber:
        class: '%lag.admin.extra_configuration_subscriber.class%'
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - '%lag.enable_extra_configuration%'
            - '@doctrine'
            - '@lag.admin.application'

    lag.admin.admin_subscriber:
        class: '%lag.admin.admin_subscriber.class%'
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - '@lag.admin.factory'

    # routing
    lag.admin.routing:
        class: '%lag.admin.routing.class%'
        tags:
            - { name: routing.loader }
        arguments:
            - '@lag.admin.factory'

    # twig
    lag.admin.twig:
        class: '%lag.admin.twig.class%'
        tags:
            - {name: twig.extension}
        arguments:
            - '@router'
            - '@translator'
            - '@lag.admin.application'

    # handler
    lag.admin.message_handler:
        class: '%lag.admin.message_handler.class%'
        arguments:
            - '@logger'
            - '@session'
            - '@translator'
