imports:
    - { resource: factories.yml }
    - { resource: forms.yml }
    - { resource: menus.yml }

services:
    # events subscribers
    lag.admin.template_subscriber:
        class: LAG\AdminBundle\Event\Subscriber\TemplateSubscriber
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - '@twig'
            - '@lag.admin.configuration_factory'

    lag.admin.extra_configuration_subscriber:
        class: LAG\AdminBundle\Event\Subscriber\ExtraConfigurationSubscriber
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - '%lag.enable_extra_configuration%'
            - '@doctrine'
            - '@lag.admin.configuration_factory'

    lag.admin.admin_subscriber:
        class: LAG\AdminBundle\Event\Subscriber\AdminSubscriber
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - '@lag.admin.factory'

    # routing
    lag.admin.routing:
        class: LAG\AdminBundle\Routing\RoutingLoader
        tags:
            - { name: routing.loader }
        arguments:
            - '@lag.admin.factory'

    # twig
    lag.admin.twig:
        class: LAG\AdminBundle\Twig\AdminExtension
        tags:
            - {name: twig.extension}
        arguments:
            - '@router'
            - '@translator'
            - '@lag.admin.configuration_factory'

    # handler
    lag.admin.message_handler:
        class: LAG\AdminBundle\Message\MessageHandler
        arguments:
            - '@logger'
            - '@session'
            - '@translator'

    # form
    lag.admin.form.factory:
        class: LAG\AdminBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
