language: php

php:
    - 7.2
    - 7.3

before_install:
    - mysql -e "create database IF NOT EXISTS admin_bundle_test;"
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then export INI=/etc/hhvm/php.ini; else export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
    - echo memory_limit = -1 >> $INI

install:
    - composer install
    - composer require phpstan/phpstan-shim
    - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer

script:
    - make phpunit.run
    - make phpstan.analyse
    - php php-cs-fixer fix --dry-run --using-cache=no --verbose

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover var/phpunit/logs/clover.xml

#env:
#    - SYMFONY_VERSION=3.4.*
#    - SYMFONY_VERSION=4.1.*
#    - SYMFONY_VERSION=4.2.*
#    - SYMFONY_VERSION=4.3.*

services:
    - mysql
