language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_install:
    - mysql -e "create database IF NOT EXISTS admin_bundle_test;"
    - cp Tests/app/config/parameters.yml.dist Tests/app/config/parameters.yml

install:
    - composer install
