services:
    php:
        build:
            context: .
        ports:
            - '8000:8000'
        volumes:
            - ./:/srv/bundle
        working_dir: /srv/bundle

    db:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_USER: admin_test
            MYSQL_PASSWORD: admin_test
            MYSQL_DATABASE: admin_test
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql

    js:
        image: node:18
        volumes:
            - .:/srv/admin-bundle
        working_dir: /srv/admin-bundle
        command: bash -c "yarn encore dev --watch"
