version: '3.4'

services:
    php:
        build:
            context: .
        ports:
            - '8000:8000'
        volumes:
            - ./:/srv/bundle
        working_dir: /srv/bundle

    db:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_USER: admin_test
            MYSQL_PASSWORD: admin_test
            MYSQL_DATABASE: admin_test
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql

    js:
        image: node:stretch-slim
        volumes:
            - .:/srv/admin-bundle
        working_dir: /home/docker/www/app
        command: bash -c "yarn encore dev --watch"

#    db:
#        image: mariadb:latest
#        ports:
#            - "3306:3306"
#        environment:
#            MYSQL_USER: admin_test
#            MYSQL_PASSWORD: admin_test
#            MYSQL_DATABASE: admin_test
#            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#        volumes:
#            - ./.docker/mysql/data_test:/var/lib/mysql
#
#    db_test:
#        image: mysql:5.7
#        ports:
#            - "3307:3306"
#        environment:
#            MYSQL_USER: admin_test
#            MYSQL_PASSWORD: admin_test
#            MYSQL_DATABASE: admin_test
#            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#        volumes:
#            - ./.docker/mysql/data:/var/lib/mysql
#
#    mailcatcher:
#        image: zolweb/docker-mailcatcher:latest
#        ports:
#            - "1080:1080"
