services:
    # Data providers
    LAG\AdminBundle\Bridge\Doctrine\ORM\State\ORMDataProvider:
        arguments:
            $registry: '@doctrine'
        tags:
            - { name: lag_admin.data_provider, identifier: doctrine }

    # Data providers
    LAG\AdminBundle\Bridge\Doctrine\ORM\State\ORMDataProcessor:
        arguments:
            $registry: '@doctrine'
        tags:
            - { name: lag_admin.data_processor, identifier: doctrine }

    # Event listeners
    LAG\AdminBundle\Bridge\Doctrine\ORM\EventListener\ResourceCreateListener:
        arguments:
            $propertyProvider: '@lag_admin.orm.property_factory'
        tags:
            - { name: kernel.event_listener, event: lag_admin.admin.create, priority: 200 }

    LAG\AdminBundle\Bridge\Doctrine\ORM\EventListener\OperationCreateListener:
        arguments:
            $filterFactory: '@lag_admin.filter.factory'
        tags:
            - { name: kernel.event_listener, event: lag_admin.operation.create, priority: 256 }

    # Property provider
    lag_admin.orm.property_factory: '@LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataPropertyFactoryInterface'
    LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataPropertyFactoryInterface:
        class: LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataPropertyFactory
        arguments:
            $metadataHelper: '@lag_admin.orm.metadata_helper'

    lag_admin.orm.metadata_helper: '@LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelperInterface'
    LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelperInterface:
        class: LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelper
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
