services:
    _defaults:
        autoconfigure: true
        autowire: true

    # Menu builders
    LAG\AdminBundle\Bridge\KnpMenu\Builder\TopMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: top }

    LAG\AdminBundle\Bridge\KnpMenu\Builder\UserMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: user }

    LAG\AdminBundle\Bridge\KnpMenu\Builder\LeftMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: left }
