services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ### Resources ###
    LAG\AdminBundle\Resource\ResourceCollection:
        class: LAG\AdminBundle\Resource\ResourceCollection
    #################

    ### Subscribers ###
    LAG\AdminBundle\Event\Subscriber\SecuritySubscriber:
        class: LAG\AdminBundle\Event\Subscriber\SecuritySubscriber

    LAG\AdminBundle\Event\Subscriber\AdminSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\AdminSubscriber

    LAG\AdminBundle\Event\Subscriber\FormSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\FormSubscriber

    LAG\AdminBundle\Event\Subscriber\ExtraConfigurationSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\ExtraConfigurationSubscriber

    LAG\AdminBundle\Event\Subscriber\MenuSubscriber:
        class: LAG\AdminBundle\Event\Subscriber\MenuSubscriber

    LAG\AdminBundle\Bridge\Doctrine\ORM\Event\Subscriber\OrmSubscriber:
        class: LAG\AdminBundle\Bridge\Doctrine\ORM\Event\Subscriber\OrmSubscriber
    ###################

    ### Configuration ###
    LAG\AdminBundle\Configuration\ApplicationConfigurationStorage:
        class: LAG\AdminBundle\Configuration\ApplicationConfigurationStorage
    #####################

    ### Routing ###
    LAG\AdminBundle\Routing\RoutingLoader:
        class: LAG\AdminBundle\Routing\RoutingLoader
        tags:
            - {name: routing.loader}
    ################

    ### Controllers ###
    LAG\AdminBundle\Controller\AdminAction:
        class: LAG\AdminBundle\Controller\AdminAction
        tags:
            - {name: controller.argument_value_resolver}

    LAG\AdminBundle\Controller\HomeAction:
        class: LAG\AdminBundle\Controller\HomeAction
        tags:
            - {name: controller.argument_value_resolver}
    ###################

    ### Factories ###
    LAG\AdminBundle\Factory\ActionFactory:
        class: LAG\AdminBundle\Factory\ActionFactory

    LAG\AdminBundle\Factory\AdminFactory:
        class: LAG\AdminBundle\Factory\AdminFactory

    LAG\AdminBundle\Factory\ConfigurationFactory:
        class: LAG\AdminBundle\Factory\ConfigurationFactory

    LAG\AdminBundle\Factory\MenuFactory:
        class: LAG\AdminBundle\Factory\MenuFactory

    LAG\AdminBundle\Factory\ViewFactory:
        class: LAG\AdminBundle\Factory\ViewFactory

    LAG\AdminBundle\Factory\DataProviderFactory:
        class: LAG\AdminBundle\Factory\DataProviderFactory

    LAG\AdminBundle\Factory\FieldFactory:
        class: LAG\AdminBundle\Factory\FieldFactory
    #################

    ### Twig extension ###
    LAG\AdminBundle\Twig\AdminExtension:
        class: LAG\AdminBundle\Twig\AdminExtension
        tags:
            - {name: twig.extension}
    ######################

    ### DataProviders ###
    LAG\AdminBundle\Bridge\Doctrine\ORM\DataProvider\ORMDataProvider:
        class: LAG\AdminBundle\Bridge\Doctrine\ORM\DataProvider\ORMDataProvider
        tags:
            - {name: lag.admin.data_provider}
    #####################
