services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    lag.admin.data_collector:
        class: LAG\AdminBundle\Debug\DataCollector\AdminDataCollector
        autowire: true
        tags:
            -
                name: data_collector
                template: '@LAGAdmin/Debug/template.html.twig'
                id: 'admin.data_collector'
        public: false

    LAG\AdminBundle\Bridge\Twig\Extension\FieldDebugExtension:
        tags:
            - {name: twig.extension}
