imports:
    resource: 'services/*'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    ### Configuration ###
    LAG\AdminBundle\Configuration\ApplicationConfigurationStorage:
        class: LAG\AdminBundle\Configuration\ApplicationConfigurationStorage
    #####################

    ### Routing ###
    LAG\AdminBundle\Routing\RoutingLoader:
        class: LAG\AdminBundle\Routing\RoutingLoader
        tags:
            - {name: routing.loader}
    ################

    ### Controllers ###
    LAG\AdminBundle\Controller\AdminAction:
        class: LAG\AdminBundle\Controller\AdminAction
        tags:
            - {name: controller.service_arguments}

    LAG\AdminBundle\Controller\HomeAction:
        class: LAG\AdminBundle\Controller\HomeAction
        tags:
            - {name: controller.service_arguments}
    ###################

    ### DataProviders ###
    LAG\AdminBundle\Bridge\Doctrine\ORM\DataProvider\ORMDataProvider:
        class: LAG\AdminBundle\Bridge\Doctrine\ORM\DataProvider\ORMDataProvider
        tags:
            - {name: lag.admin.data_provider}
    #####################

    LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelper: ~
    LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelperInterface: '@LAG\AdminBundle\Bridge\Doctrine\ORM\Metadata\MetadataHelper'
