services:
    lag.admin.actions.list:
        class: LAG\AdminBundle\Controller\ListAction
        autowire: true
        arguments:
            - list

    lag.admin.actions.create:
        class: LAG\AdminBundle\Controller\CreateAction
        autowire: true
        arguments:
            - create

    lag.admin.actions.edit:
        class: LAG\AdminBundle\Controller\EditAction
        autowire: true
        arguments:
            - edit

    lag.admin.actions.delete:
        class: LAG\AdminBundle\Controller\DeleteAction
        autowire: true
        arguments:
            - delete
