services:
    lag.admin.factory:
        class: LAG\AdminBundle\Admin\Factory\AdminFactory
        autowire: true
        arguments:
            - '%lag.admins%'
            - '@event_dispatcher'

    lag.admin.action_factory:
        class: LAG\AdminBundle\Action\Factory\ActionFactory
        autowire: true

    lag.admin.action_configuration_factory:
        class: LAG\AdminBundle\Action\Factory\ConfigurationFactory
        autowire: true

    lag.admin.admin_configuration_factory:
        class: LAG\AdminBundle\Admin\Factory\ConfigurationFactory
        autowire: true

    lag.admin.field_factory:
        class: LAG\AdminBundle\Field\Factory\FieldFactory
        autowire: true

    lag.admin.menu_factory:
        class: LAG\AdminBundle\Menu\Factory\MenuFactory
        autowire: true

    lag.admin.data_providers_factory:
        class: LAG\AdminBundle\DataProvider\Factory\DataProviderFactory
        autowire: true

    lag.admin.field_configuration_factory:
        class: LAG\AdminBundle\Field\Factory\ConfigurationFactory
        autowire: true
