services:
    # Forms
    lag.admin.form.datetime_picker:
        class: LAG\AdminBundle\Form\Type\DateTimePickerType
        tags:
            - {name: form.type, alias: datetime_picker}

    # Handlers
    lag.admin.form.edit_form_handler:
        class: LAG\AdminBundle\Form\Handler\EditFormHandler
        autowire: true
        tags:
            - {name: lag.admin.form_handler}

    lag.admin.form.list_form_handler:
        class: LAG\AdminBundle\Form\Handler\ListFormHandler
        autowire: true
        tags:
            - {name: lag.admin.form_handler}

    # Factories
    lag.admin.form.factory:
        class: LAG\AdminBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
