services:
    # Responders
    lag.admin.action.list_responder:
        class: LAG\AdminBundle\Action\Responder\ListResponder
        autowire: true
        tags:
            - {name: responder}

    lag.admin.responder.storage:
        class: LAG\AdminBundle\Responder\Storage\ResponderStorage
