jk_sam:
    debug: false
    filters:
        compass: ~
        merge: ~
        minify: ~
        copy: ~
    tasks:
        admin.css:
            filters:
                - compass
                - merge
                - minify
            sources:
                - vendor/components/bootstrap/css/bootstrap.min.css
                - vendor/components/font-awesome/css/font-awesome.min.css
                - src/LAG/AdminBundle/Resources/assets/scss/*
            destinations:
                - src/LAG/AdminBundle/Resources/public/css/admin.css

        admin.js:
            filters:
                - merge
                - minify
            sources:
                - src/LAG/AdminBundle/Resources/assets/js/*
                - vendor/components/jquery/jquery.min.js
                - vendor/components/bootstrap/js/bootstrap.min.js
            destinations:
                - src/LAG/AdminBundle/Resources/public/js/admin.js

        fonts:
            filters: ~
            sources:
                - vendor/components/font-awesome/fonts/
            destinations:
                - src/LAG/AdminBundle/Resources/public/fonts/
