imports:
    - {resource: factories.yml}
    - {resource: forms.yml}
    - {resource: menus.yml}
    - {resource: actions.yml}
    
services:
    # Events subscribers
    lag.admin.kernel_subscriber:
        class: LAG\AdminBundle\Event\Subscriber\KernelSubscriber
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - '@lag.admin.factory'
            - '@lag.admin.action_factory'
            - '@lag.admin.request_handler'

    lag.admin.extra_configuration_subscriber:
        class: LAG\AdminBundle\Event\Subscriber\ExtraConfigurationSubscriber
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - '%lag.enable_extra_configuration%'
            - '@doctrine'
            - '@lag.admin.configuration_factory'

    # Routing loader
    lag.admin.routing:
        class: LAG\AdminBundle\Routing\RoutingLoader
        tags:
            - { name: routing.loader }
        arguments:
            - '@lag.admin.factory'
            - '@lag.admin.registry'
            - '@lag.admin.configuration_factory'

    # Twig extension
    lag.admin.twig:
        class: LAG\AdminBundle\Twig\AdminExtension
        tags:
            - {name: twig.extension}
        arguments:
            - '@router'
            - '@translator'
            - '%lag.translation_pattern%'

    # Message handlers
    lag.admin.message_handler:
        class: LAG\AdminBundle\Message\MessageHandler
        arguments:
            - '@logger'
            - '@session'
            - '@translator'

    # Request handler
    lag.admin.request_handler:
        class: LAG\AdminBundle\Admin\Request\RequestHandler
        arguments:
            - '@lag.admin.registry'

    # Registry
    lag.admin.registry:
        class: LAG\AdminBundle\Admin\Registry\Registry

    lag.admin.action_registry:
        class: LAG\AdminBundle\Action\Registry\Registry

    # Filters
    lag.admin.filter_form_builder:
        class: LAG\AdminBundle\Filter\Factory\FilterFormBuilder
        autowire: true

    # Responders
    lag.admin.action.list_responder:
        class: LAG\AdminBundle\Action\Responder\ListResponder
        autowire: true
