lag_admin.login:
    path: /login
    controller: LAG\AdminBundle\Controller\LoginAction
    defaults:
        template: '@LAGAdmin/security/login.html.twig'

lag_admin.login_check:
    path: /login-check
    controller: LAG\AdminBundle\Controller\LoginAction

lag_admin.logout:
    path: /logout

lag_admin.homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: '@@LAGAdmin/pages/home.html.twig'

lag_admin:
    resource: .
    type: lag_admin
