imports:
    - {resource: 'services/*'}
    - {resource: 'services/bridge/*'}

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ### Controllers ###
    LAG\AdminBundle\Controller\AdminAction:
        tags:
            - {name: controller.service_arguments}

    LAG\AdminBundle\Controller\HomeAction:
        tags:
            - {name: controller.service_arguments}
    ###################


