<?php

declare(strict_types=1);

namespace LAG\AdminBundle\Tests\Config\Mapper;

use LAG\AdminBundle\Config\Mapper\GridMapper;
use LAG\AdminBundle\Metadata\Action;
use LAG\AdminBundle\Metadata\Grid;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

final class GridMapperTest extends TestCase
{
    #[Test]
    public function itMapsAnArrayToAGrid(): void
    {
        $expectedGrid = new Grid(
            name: 'my_grid',
            title: 'My Grid',
            type: 'table',
            template: 'my_grid.html.twig',
            component: 'some_component',
            translationDomain: 'my_translation_domain',
            properties: ['name', 'enabled', 'images'],
            attributes: ['class' => 'my_class'],
            rowAttributes: ['class' => 'my_class'],
            containerAttributes: ['class' => 'my_class'],
            actionCellAttributes: ['class' => 'my_class'],
            headerTemplate: 'header_template.html.twig',
            headerRowAttributes: ['class' => 'my_class'],
            headerAttributes: ['class' => 'my_header_class'],
            options: ['some_option' => 'some_value'],
            form: 'SomeForm',
            formOptions: ['some_option' => 'some_value'],
            actions: [new Action(
                name: 'some_action',
                propertyPath: 'somePath',
                label: 'My Action',
                template: 'action.html.twig',
                translatable: true,
                translationDomain: 'a_translation_domain',
                attributes: ['id' => 'my-action'],
                rowAttributes: ['class' => 'row-class'],
                headerAttributes: ['class' => 'header-class'],
                dataTransformer: 'SomeDataTransformer',
                permissions: ['ROLE_ADMIN'],
                condition: '$data.isEnabled()',
                sortingPath: 'someSortingPath',
            )],
            collectionActions: [new Action(
                name: 'some_action',
                propertyPath: 'somePath',
                label: 'My Action',
                template: 'action.html.twig',
                translatable: true,
                translationDomain: 'a_translation_domain',
                attributes: ['id' => 'my-action'],
                rowAttributes: ['class' => 'row-class'],
                headerAttributes: ['class' => 'header-class'],
                dataTransformer: 'SomeDataTransformer',
                permissions: ['ROLE_ADMIN'],
                condition: '$data.isEnabled()',
                sortingPath: 'someSortingPath',
            )],
            emptyMessage: 'No record',
            sortable: true,
        );

        $config = [
            'name' => 'my_grid',
            'title' => 'My Grid',
            'type' => 'table',
            'template' => 'my_grid.html.twig',
            'component' => 'some_component',
            'translation_domain' => 'my_translation_domain',
            'properties' => ['name', 'enabled', 'images'],
            'attributes' => ['class' => 'my_class'],
            'row_attributes' => ['class' => 'my_class'],
            'container_attributes' => ['class' => 'my_class'],
            'action_cell_attributes' => ['class' => 'my_class'],
            'header_template' => 'header_template.html.twig',
            'header_row_attributes' => ['class' => 'my_class'],
            'header_attributes' => ['class' => 'my_header_class'],
            'options' => ['some_option' => 'some_value'],
            'form' => 'SomeForm',
            'form_options' => ['some_option' => 'some_value'],
            'actions' => [
                [
                    'name' => 'some_action',
                    'property_path' => 'somePath',
                    'label' => 'My Action',
                    'template' => 'action.html.twig',
                    'translatable' => true,
                    'translation_domain' => 'a_translation_domain',
                    'attributes' => ['id' => 'my-action'],
                    'row_attributes' => ['class' => 'row-class'],
                    'header_attributes' => ['class' => 'header-class'],
                    'data_transformer' => 'SomeDataTransformer',
                    'permissions' => ['ROLE_ADMIN'],
                    'condition' => '$data.isEnabled()',
                    'sorting_path' => 'someSortingPath',
                ],
            ],
            'collection_actions' => [
                [
                    'name' => 'some_action',
                    'property_path' => 'somePath',
                    'label' => 'My Action',
                    'template' => 'action.html.twig',
                    'translatable' => true,
                    'translation_domain' => 'a_translation_domain',
                    'attributes' => ['id' => 'my-action'],
                    'row_attributes' => ['class' => 'row-class'],
                    'header_attributes' => ['class' => 'header-class'],
                    'data_transformer' => 'SomeDataTransformer',
                    'permissions' => ['ROLE_ADMIN'],
                    'condition' => '$data.isEnabled()',
                    'sorting_path' => 'someSortingPath',
                ],
            ],
            'empty_message' => 'No record',
            'sortable' => true,
        ];

        $grid = new GridMapper()->fromArray($config);

        self::assertEquals($expectedGrid, $grid);
    }

    #[Test]
    public function itMapsAGridToAnArray(): void
    {
        $grid = new Grid(
            name: 'my_grid',
            title: 'My Grid',
            type: 'table',
            template: 'my_grid.html.twig',
            component: 'some_component',
            translationDomain: 'my_translation_domain',
            properties: ['name', 'enabled', 'images'],
            attributes: ['class' => 'my_class'],
            rowAttributes: ['class' => 'my_class'],
            containerAttributes: ['class' => 'my_class'],
            actionCellAttributes: ['class' => 'my_class'],
            headerTemplate: 'header_template.html.twig',
            headerRowAttributes: ['class' => 'my_class'],
            headerAttributes: ['class' => 'my_header_class'],
            options: ['some_option' => 'some_value'],
            form: 'SomeForm',
            formOptions: ['some_option' => 'some_value'],
            actions: [new Action(
                name: 'some_action',
                propertyPath: 'somePath',
                label: 'My Action',
                template: 'action.html.twig',
                translatable: true,
                translationDomain: 'a_translation_domain',
                attributes: ['id' => 'my-action'],
                rowAttributes: ['class' => 'row-class'],
                headerAttributes: ['class' => 'header-class'],
                dataTransformer: 'SomeDataTransformer',
                permissions: ['ROLE_ADMIN'],
                condition: '$data.isEnabled()',
                sortingPath: 'someSortingPath',
            )],
            collectionActions: [new Action(
                name: 'some_action',
                propertyPath: 'somePath',
                label: 'My Action',
                template: 'action.html.twig',
                translatable: true,
                translationDomain: 'a_translation_domain',
                attributes: ['id' => 'my-action'],
                rowAttributes: ['class' => 'row-class'],
                headerAttributes: ['class' => 'header-class'],
                dataTransformer: 'SomeDataTransformer',
                permissions: ['ROLE_ADMIN'],
                condition: '$data.isEnabled()',
                sortingPath: 'someSortingPath',
            )],
            emptyMessage: 'No record',
            sortable: true,
        );
        $config = new GridMapper()->toArray($grid);
        $expectedConfig = [
            'name' => 'my_grid',
            'title' => 'My Grid',
            'type' => 'table',
            'template' => 'my_grid.html.twig',
            'component' => 'some_component',
            'translation_domain' => 'my_translation_domain',
            'properties' => ['name', 'enabled', 'images'],
            'attributes' => ['class' => 'my_class'],
            'row_attributes' => ['class' => 'my_class'],
            'container_attributes' => ['class' => 'my_class'],
            'action_cell_attributes' => ['class' => 'my_class'],
            'header_template' => 'header_template.html.twig',
            'header_row_attributes' => ['class' => 'my_class'],
            'header_attributes' => ['class' => 'my_header_class'],
            'options' => ['some_option' => 'some_value'],
            'form' => 'SomeForm',
            'form_options' => ['some_option' => 'some_value'],
            'actions' => [
                [
                    'name' => 'some_action',
                    'property_path' => 'somePath',
                    'label' => 'My Action',
                    'template' => 'action.html.twig',
                    'translatable' => true,
                    'translation_domain' => 'a_translation_domain',
                    'attributes' => ['id' => 'my-action'],
                    'row_attributes' => ['class' => 'row-class'],
                    'header_attributes' => ['class' => 'header-class'],
                    'data_transformer' => 'SomeDataTransformer',
                    'permissions' => ['ROLE_ADMIN'],
                    'condition' => '$data.isEnabled()',
                    'sorting_path' => 'someSortingPath',
                    'route' => null,
                    'route_parameters' => [],
                    'application' => null,
                    'resource' => null,
                    'operation' => null,
                    'url' => null,
                    'type' => null,
                    'icon' => null,
                    'workflow' => null,
                    'title' => null,
                    'sortable' => false,
                ],
            ],
            'collection_actions' => [
                [
                    'name' => 'some_action',
                    'property_path' => 'somePath',
                    'label' => 'My Action',
                    'template' => 'action.html.twig',
                    'translatable' => true,
                    'translation_domain' => 'a_translation_domain',
                    'attributes' => ['id' => 'my-action'],
                    'row_attributes' => ['class' => 'row-class'],
                    'header_attributes' => ['class' => 'header-class'],
                    'data_transformer' => 'SomeDataTransformer',
                    'permissions' => ['ROLE_ADMIN'],
                    'condition' => '$data.isEnabled()',
                    'sorting_path' => 'someSortingPath',
                    'route' => null,
                    'route_parameters' => [],
                    'application' => null,
                    'resource' => null,
                    'operation' => null,
                    'url' => null,
                    'type' => null,
                    'icon' => null,
                    'workflow' => null,
                    'title' => null,
                    'sortable' => false,
                ],
            ],
            'empty_message' => 'No record',
            'sortable' => true,
        ];

        self::assertEquals($expectedConfig, $config);
    }
}
