<?php

declare(strict_types=1);

namespace LAG\AdminBundle\Tests\Config\Mapper;

use LAG\AdminBundle\Config\Mapper\ResourceMapper;
use LAG\AdminBundle\Controller\Resource\IndexResources;
use LAG\AdminBundle\Controller\Resource\ShowResource;
use LAG\AdminBundle\Form\Type\Resource\FilterType;
use LAG\AdminBundle\Metadata\Boolean;
use LAG\AdminBundle\Metadata\Index;
use LAG\AdminBundle\Metadata\Resource;
use LAG\AdminBundle\Metadata\Show;
use LAG\AdminBundle\Metadata\Text;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

final class ResourceMapperTest extends TestCase
{
    #[Test]
    public function itMapsAResourceToAnArray(): void
    {
        $resource = new Resource(
            name: 'MyResource',
            resourceClass: 'MyEntity',
            title: 'Some Title',
            group: 'some group',
            icon: 'icon.png',
            operations: [
                new Index(
                    provider: 'IndexProvider',
                    processor: 'IndexProcessor',
                ),
                new Show(
                    provider: 'ShowProvider',
                    processor: 'ShowProcessor',
                ),
            ],
            properties: [
                new Text(
                    name: 'label',
                    translatable: true,
                    translationDomain: 'messages',
                ),
                new Boolean(name: 'enabled'),
            ],
            provider: 'ResourceProvider',
            processor: 'ResourceProcessor',
            identifiers: ['id'],
            routePattern: '{application}.{resource}.{operation}',
            translationPattern: '{resource}.{operation}',
            translationDomain: 'messages',
            pathPrefix: '/operations',
            permissions: ['ROLE_ADMIN'],
            form: 'MyForm',
            formOptions: ['an_option' => 'a_value'],
            formTemplate: 'form.html.twig',
            validation: true,
            validationContext: ['groups' => 'my_group'],
            ajax: false,
            normalizationContext: ['groups' => 'my_group'],
            denormalizationContext: ['groups' => 'my_group'],
            input: 'MyInput',
            output: 'MyOutput',
        );
        $expectedData = [
            'name' => 'MyResource',
            'application' => 'admin',
            'resource_class' => 'MyEntity',
            'title' => 'Some Title',
            'group' => 'some group',
            'icon' => 'icon.png',
            'path_prefix' => '/operations',
            'permissions' => ['ROLE_ADMIN'],
            'operations' => [
                [
                    'short_name' => 'index',
                    'name' => null,
                    'pagination' => true,
                    'items_per_page' => 25,
                    'page_parameter' => 'page',
                    'criteria' => [],
                    'order_by' => [],
                    'filters' => [],
                    'grid' => null,
                    'grid_options' => [],
                    'collection_actions' => null,
                    'filter_form' => FilterType::class,
                    'filter_form_options' => [],
                    'item_form' => null,
                    'item_form_options' => null,
                    'collection_form' => null,
                    'collection_form_options' => null,
                    'redirect_route_parameters' => [],
                    'form' => null,
                    'form_options' => null,
                    'form_template' => null,
                    'processor' => 'IndexProcessor',
                    'provider' => 'IndexProvider',
                    'identifiers' => null,
                    'contextual_actions' => null,
                    'item_actions' => null,
                    'redirect_operation' => null,
                    'validation' => true,
                    'validation_context' => null,
                    'ajax' => true,
                    'normalization_context' => null,
                    'denormalization_context' => null,
                    'input' => null,
                    'output' => null,
                    'workflow' => null,
                    'workflow_transition' => null,
                    'partial' => false,
                    'success_message' => null,
                    'class' => 'LAG\AdminBundle\Metadata\Index',
                    'resource' => null,
                    'context' => [],
                    'title' => null,
                    'description' => null,
                    'icon' => null,
                    'template' => '@LAGAdmin/resources/index.html.twig',
                    'base_template' => null,
                    'permissions' => null,
                    'controller' => IndexResources::class,
                    'route' => null,
                    'route_parameters' => [],
                    'methods' => [],
                    'path' => null,
                    'redirect_route' => null,
                ],
                [
                    'short_name' => 'show',
                    'name' => null,
                    'resource' => null,
                    'context' => [],
                    'title' => null,
                    'description' => null,
                    'icon' => null,
                    'template' => '@LAGAdmin/resources/show.html.twig',
                    'base_template' => null,
                    'permissions' => null,
                    'controller' => ShowResource::class,
                    'route' => null,
                    'route_parameters' => null,
                    'methods' => ['GET'],
                    'path' => null,
                    'redirect_route' => null,
                    'redirect_route_parameters' => null,
                    'form' => null,
                    'form_options' => null,
                    'form_template' => null,
                    'processor' => 'ShowProcessor',
                    'provider' => 'ShowProvider',
                    'identifiers' => null,
                    'contextual_actions' => null,
                    'item_actions' => null,
                    'redirect_operation' => null,
                    'validation' => true,
                    'validation_context' => null,
                    'ajax' => true,
                    'normalization_context' => null,
                    'denormalization_context' => null,
                    'input' => null,
                    'output' => null,
                    'workflow' => null,
                    'workflow_transition' => null,
                    'partial' => false,
                    'success_message' => null,
                    'class' => 'LAG\AdminBundle\Metadata\Show',
                ],
            ],
            'properties' => [
                'label' => [
                    '__class__' => Text::class,
                    'name' => 'label',
                    'length' => 100,
                    'replace' => '...',
                    'empty' => '~',
                    'suffix' => '',
                    'prefix' => '',
                    'translatable' => true,
                    'translation_domain' => 'messages',
                    'attributes' => [],
                    'row_attributes' => [],
                    'header_attributes' => [],
                    'data_transformer' => null,
                    'permissions' => null,
                    'condition' => null,
                    'sorting_path' => null,
                    'property_path' => null,
                    'label' => null,
                    'template' => '@LAGAdmin/grids/properties/text.html.twig',
                    'sortable' => true,
                ],
                'enabled' => [
                    '__class__' => Boolean::class,
                    'name' => 'enabled',
                    'property_path' => null,
                    'label' => null,
                    'template' => '@LAGAdmin/grids/properties/boolean.html.twig',
                    'sortable' => true,
                    'translatable' => true,
                    'translation_domain' => null,
                    'attributes' => [],
                    'row_attributes' => [],
                    'header_attributes' => [],
                    'data_transformer' => null,
                    'permissions' => null,
                    'condition' => null,
                    'sorting_path' => null,
                ],
            ],
            'processor' => 'ResourceProcessor',
            'provider' => 'ResourceProvider',
            'identifiers' => ['id'],
            'route_pattern' => '{application}.{resource}.{operation}',
            'translation_pattern' => '{resource}.{operation}',
            'translation_domain' => 'messages',
            'form' => 'MyForm',
            'form_options' => ['an_option' => 'a_value'],
            'form_template' => 'form.html.twig',
            'validation' => true,
            'validation_context' => ['groups' => 'my_group'],
            'ajax' => false,
            'normalization_context' => ['groups' => 'my_group'],
            'denormalization_context' => ['groups' => 'my_group'],
            'input' => 'MyInput',
            'output' => 'MyOutput',
        ];

        $mapper = new ResourceMapper();
        $data = $mapper->toArray($resource);

        self::assertEquals($expectedData, $data);
    }

    #[Test]
    public function itMapsAnArrayToAResource(): void
    {
        $data = [
            'name' => 'MyResource',
            'application' => 'admin',
            'resource_class' => 'MyEntity',
            'title' => 'Some Title',
            'group' => 'some group',
            'icon' => 'icon.png',
            'path_prefix' => '/operations',
            'permissions' => ['ROLE_ADMIN'],
            'operations' => [
                [
                    'pagination' => true,
                    'items_per_page' => 25,
                    'page_parameter' => 'page',
                    'criteria' => [],
                    'order_by' => [],
                    'filters' => [],
                    'grid' => null,
                    'grid_options' => [],
                    'collection_actions' => null,
                    'filter_form' => FilterType::class,
                    'filter_form_options' => [],
                    'item_form' => null,
                    'item_form_options' => null,
                    'collection_form' => null,
                    'collection_form_options' => null,
                    'redirect_route_parameters' => [],
                    'form' => null,
                    'form_options' => null,
                    'form_template' => null,
                    'processor' => 'IndexProcessor',
                    'provider' => 'IndexProvider',
                    'identifiers' => null,
                    'contextual_actions' => null,
                    'item_actions' => null,
                    'redirect_operation' => null,
                    'validation' => true,
                    'validation_context' => null,
                    'ajax' => true,
                    'normalization_context' => null,
                    'denormalization_context' => null,
                    'input' => null,
                    'output' => null,
                    'workflow' => null,
                    'workflow_transition' => null,
                    'partial' => false,
                    'success_message' => null,
                    'class' => 'LAG\AdminBundle\Metadata\Index',
                    'resource' => null,
                    'name' => 'index',
                    'context' => [],
                    'title' => null,
                    'description' => null,
                    'icon' => null,
                    'template' => '@LAGAdmin/resources/index.html.twig',
                    'base_template' => null,
                    'permissions' => null,
                    'controller' => IndexResources::class,
                    'route' => null,
                    'route_parameters' => [],
                    'methods' => [],
                    'path' => null,
                    'redirect_route' => null,
                ],
                [
                    'name' => 'show',
                    'resource' => null,
                    'context' => [],
                    'title' => null,
                    'description' => null,
                    'icon' => null,
                    'template' => '@LAGAdmin/resources/show.html.twig',
                    'base_template' => null,
                    'permissions' => null,
                    'controller' => ShowResource::class,
                    'route' => null,
                    'route_parameters' => null,
                    'methods' => ['GET'],
                    'path' => null,
                    'redirect_route' => null,
                    'redirect_route_parameters' => null,
                    'form' => null,
                    'form_options' => null,
                    'form_template' => null,
                    'processor' => 'ShowProcessor',
                    'provider' => 'ShowProvider',
                    'identifiers' => null,
                    'contextual_actions' => null,
                    'item_actions' => null,
                    'redirect_operation' => null,
                    'validation' => true,
                    'validation_context' => null,
                    'ajax' => true,
                    'normalization_context' => null,
                    'denormalization_context' => null,
                    'input' => null,
                    'output' => null,
                    'workflow' => null,
                    'workflow_transition' => null,
                    'partial' => false,
                    'success_message' => null,
                    'class' => 'LAG\AdminBundle\Metadata\Show',
                ],
            ],
            'properties' => [
                [
                    '__class__' => Text::class,
                    'name' => 'label',
                    'length' => 100,
                    'replace' => '...',
                    'empty' => '~',
                    'suffix' => '',
                    'prefix' => '',
                    'translatable' => true,
                    'translation_domain' => 'messages',
                    'attributes' => [],
                    'row_attributes' => [],
                    'header_attributes' => [],
                    'data_transformer' => null,
                    'permissions' => null,
                    'condition' => null,
                    'sorting_path' => null,
                    'property_path' => null,
                    'label' => null,
                    'template' => '@LAGAdmin/grids/properties/text.html.twig',
                    'sortable' => true,
                ],
                [
                    '__class__' => Boolean::class,
                    'name' => 'enabled',
                ],
            ],
            'processor' => 'ResourceProcessor',
            'provider' => 'ResourceProvider',
            'identifiers' => ['id'],
            'route_pattern' => '{application}.{resource}.{operation}',
            'translation_pattern' => '{resource}.{operation}',
            'translation_domain' => 'messages',
            'form' => 'MyForm',
            'form_options' => ['an_option' => 'a_value'],
            'form_template' => 'form.html.twig',
            'validation' => true,
            'validation_context' => ['groups' => 'my_group'],
            'ajax' => false,
            'normalization_context' => ['groups' => 'my_group'],
            'denormalization_context' => ['groups' => 'my_group'],
            'input' => 'MyInput',
            'output' => 'MyOutput',
        ];

        $expectedResource = new Resource(
            name: 'MyResource',
            resourceClass: 'MyEntity',
            title: 'Some Title',
            group: 'some group',
            icon: 'icon.png',
            operations: [
                'index' => new Index(
                    provider: 'IndexProvider',
                    processor: 'IndexProcessor',
                ),
                'show' => new Show(
                    provider: 'ShowProvider',
                    processor: 'ShowProcessor',
                ),
            ],
            properties: [
                new Text(
                    name: 'label',
                    translatable: true,
                    translationDomain: 'messages',
                ),
                new Boolean(
                    name: 'enabled',
                ),
            ],
            provider: 'ResourceProvider',
            processor: 'ResourceProcessor',
            identifiers: ['id'],
            routePattern: '{application}.{resource}.{operation}',
            translationPattern: '{resource}.{operation}',
            translationDomain: 'messages',
            pathPrefix: '/operations',
            permissions: ['ROLE_ADMIN'],
            form: 'MyForm',
            formOptions: ['an_option' => 'a_value'],
            formTemplate: 'form.html.twig',
            validation: true,
            validationContext: ['groups' => 'my_group'],
            ajax: false,
            normalizationContext: ['groups' => 'my_group'],
            denormalizationContext: ['groups' => 'my_group'],
            input: 'MyInput',
            output: 'MyOutput',
        );

        $mapper = new ResourceMapper();
        $resource = $mapper->fromArray($data);

        self::assertEquals($expectedResource, $resource);
    }
}
