name: Build and Test AdminBundle

on:
    - push

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        env:
            extensions: json
            composer_version: 2
        strategy:
            matrix:
                php_version:
                    - '8.3'
        steps:
            -   uses: actions/checkout@v3

            -   name: Cache vendors
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.composer/cache
                    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

            -   name: Setup PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    extensions: ${{ env.extensions }}
                    ini-values: memory_limit=-1
                    coverage: pcov
                    tools: composer, php-cs-fixer, cs2pr

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Install yarn dependencies
                run: yarn install --force

            -   name: Build yarn dependencies
                run: yarn run encore production

            -   name: Run docker compose
                run: docker compose up -d db

            -   name: Run phpunit
                run: bin/phpunit -c phpunit.xml.dist

            -   name: Run php-cs-fixer
                run: PHP_CS_FIXER_IGNORE_ENV=1 php-cs-fixer fix --dry-run --using-cache=no --verbose --diff --allow-risky=yes --config .php-cs-fixer.dist.php

            -   name: Run phpstan
                run: bin/phpstan analyse --level=5 src

            -   name: Run var_dump checker
                run: bin/var-dump-check --symfony src tests
